// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0bNWWkc4wk6RPJb8VaKwSCw_yuk2FEMI',
    appId: '1:693144893178:web:b386563be0dc4b1008bb43',
    messagingSenderId: '693144893178',
    projectId: 'fiqahbookingapp-86ce9',
    authDomain: 'fiqahbookingapp-86ce9.firebaseapp.com',
    storageBucket: 'fiqahbookingapp-86ce9.firebasestorage.app',
    measurementId: 'G-78Y5YM31LM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2zBwsvV3SgXw6OxS5u_VEYP3puJm1SMM',
    appId: '1:693144893178:android:293b1b51057a3d1808bb43',
    messagingSenderId: '693144893178',
    projectId: 'fiqahbookingapp-86ce9',
    storageBucket: 'fiqahbookingapp-86ce9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGqDv5xQdhSzBtkbDjACksM8eeHDAW0_M',
    appId: '1:693144893178:ios:354eac572fe3d2bb08bb43',
    messagingSenderId: '693144893178',
    projectId: 'fiqahbookingapp-86ce9',
    storageBucket: 'fiqahbookingapp-86ce9.firebasestorage.app',
    iosBundleId: 'com.example.serviceapplication01',
  );

}